version: '3'

services:

  web:
    build: .
    container_name: webapp
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - EMAIL_USER={EMAIL_USER}
      - EMAIL_PASS={EMAIL_PASS}
      - RESEND_API_KEY={RESEND_API_KEY}
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    restart: always
    container_name: eshopbd
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
